name: Run Ubuntu Container

on:
  push:
    branches:
      - main  # Hangi branch'te çalıştırılacak?

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu'yu seçiyoruz

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Depoyu çek

    - name: Run Ubuntu Container
      run: |
        sudo apt update && sudo apt install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo docker run -d ubuntu:latest sleep 86400  # Geçici Ubuntu container'ı çalıştır
